#%RAML 1.0
---
title: Plagiarism Identify Server
documentation:
  - title: Copyright
    content: |
      Copyright (c) 2021 AimerNeige\
      aimer.neige@aimerneige.com\
      All rights reserved.
baseUri: http://example.com/api/{version}
version: v1


traits:
  hasAuth:
    headers:
      Authorization:
        type: string
        description: Bearer token
        example:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjEsIklzVGVhY2hlciI6dHJ1ZSwiZXhwIjoxNjMzNTMxNzU4LCJpYXQiOjE2MzM1MjQ1NTgsImlzcyI6ImFpbWVybmVpZ2UuY29tIiwic3ViIjoidXNlciB0b2tlbiJ9.EnJnAvSklGaem0bOllDCL1TI--yTFfs_WHU7qeOYhiw
        required: true

/login:
  description: 用户登录
  /teacher:
    description: 老师登录
    get:
      description: 登录获取 token
      body:
        multipart/form-data:
          properties:
            account:
              type: string
              description: 用户帐号
              example: 1907040101
              required: true
            password:
              type: string
              description: 用户密码
              example: password1234
              required: true
      responses:
        200:
          body:
            application/json:
              example: !include api-include-login-teacher-get-return-sample.json
  /student:
    description: 学生登录
    get:
      description: 登录获取 token
      body:
        multipart/form-data:
          properties:
            account:
              type: string
              description: 用户帐号
              example: 1907040101
              required: true
            password:
              type: string
              description: 用户密码
              example: password1234
              required: true
      responses:
        200:
          body:
            application/json:
              example: !include api-include-login-student-get-return-sample.json
/student:
  description: 学生相关接口
  post:
    description: 注册学生帐号
    body:
      multipart/form-data:
        properties:
          account:
            type: string
            description: 用户帐号
            example: 1907040101
            required: true
          password:
            type: string
            description: 用户密码
            example: password1234
            required: true
    responses:
      201:
        body:
          application/json:
            example: !include api-include-student-post-return-sample.json
  /{id}:
    uriParameters:
      id:
        description: 用户 id
        type: integer
    get:
      is: ["hasAuth"]
      description: 获取学生信息
      responses:
        200:
          body:
            application/json:
              example: !include api-include-student-id-get-return-sample.json
    put:
      is: ["hasAuth"]
      description: 更新学生信息
      body:
        multipart/form-data:
          properties:
            name:
              type: string
              description: 姓名
              example: 张三
              required: true
            phone:
              type: string
              description: 手机号
              example: 13735667891
              required: true
            email:
              type: string
              description: 邮箱
              example: user@example.com
              required: true
      responses:
        200:
          body:
            application/json:
              example: !include api-include-student-id-put-return-sample.json
    delete:
      is: ["hasAuth"]
      description: 注销学生帐号
      responses:
        200:
          body:
            application/json:
              example: !include api-include-student-id-delete-return-sample.json
    /avatar:
      description: 用户头像相关接口
      get:
        is: ["hasAuth"]
        description: 获取用户头像
        responses:
          200:
            body:
              application/json:
                example: !include api-include-student-id-avatar-get-return-sample.json
      put:
        is: ["hasAuth"]
        description: 修改用户头像
        body:
          multipart/form-data:
            properties:
              avatar:
                type: file
                fileTypes: ['image/jpeg', 'image/png']
                maxLength: 307200
                description: 头像
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-student-id-avatar-put-return-sample.json
    /name:
      description: 用户姓名相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户姓名
        body:
          multipart/form-data:
            properties:
              name:
                type: string
                description: 姓名
                example: 张三
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-student-id-name-put-return-sample.json
    /phone:
      description: 用户手机号相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户手机号
        body:
          multipart/form-data:
            properties:
              phone:
                type: string
                description: 手机号
                example: 13735667891
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-student-id-phone-put-return-sample.json
    /email:
      description: 用户邮箱相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户邮箱
        body:
          multipart/form-data:
            properties:
              email:
                type: string
                description: 邮箱
                example: user@example.com
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-student-id-email-put-return-sample.json
    /password:
      description: 用户密码相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户密码
        body:
          multipart/form-data:
            properties:
              old:
                type: string
                description: 旧密码
                example: password123
                required: true
              new:
                type: string
                description: 新密码
                example: passcode123
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-student-id-password-put-return-sample.json
/teacher:
  description: 教师相关接口
  post:
    description: 注册教师帐号
    body:
      multipart/form-data:
        properties:
          account:
            type: string
            description: 用户帐号
            example: 1907040101
            required: true
          password:
            type: string
            description: 用户密码
            example: password1234
            required: true
    responses:
      201:
        body:
          application/json:
            example: !include api-include-teacher-post-return-sample.json
  /{id}:
    uriParameters:
      id:
        description: 用户 id
        type: integer
    get:
      is: ["hasAuth"]
      description: 获取教师信息
      responses:
        200:
          body:
            application/json:
              example: !include api-include-teacher-id-get-return-sample.json
    put:
      is: ["hasAuth"]
      description: 更新教师信息
      body:
        multipart/form-data:
          properties:
            name:
              type: string
              description: 姓名
              example: 张三
              required: true
            phone:
              type: string
              description: 手机号
              example: 13735667891
              required: true
            email:
              type: string
              description: 邮箱
              example: user@example.com
              required: true
      responses:
        200:
          body:
            application/json:
              example: !include api-include-teacher-id-put-return-sample.json
    delete:
      is: ["hasAuth"]
      description: 注销教师帐号
      responses:
        200:
          body:
            application/json:
              example: !include api-include-teacher-id-delete-return-sample.json
    /avatar:
      description: 用户头像相关接口
      get:
        is: ["hasAuth"]
        description: 获取用户头像
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-avatar-get-return-sample.json
      put:
        is: ["hasAuth"]
        description: 修改用户头像
        body:
          multipart/form-data:
            properties:
              avatar:
                type: file
                fileTypes: ['image/jpeg', 'image/png']
                maxLength: 307200
                description: 头像
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-avatar-put-return-sample.json
    /name:
      description: 用户姓名相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户姓名
        body:
          multipart/form-data:
            properties:
              name:
                type: string
                description: 姓名
                example: 张三
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-name-put-return-sample.json
    /phone:
      description: 用户手机号相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户手机号
        body:
          multipart/form-data:
            properties:
              phone:
                type: string
                description: 手机号
                example: 13735667891
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-phone-put-return-sample.json
    /email:
      description: 用户邮箱相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户邮箱
        body:
          multipart/form-data:
            properties:
              email:
                type: string
                description: 邮箱
                example: user@example.com
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-email-put-return-sample.json
    /password:
      description: 用户密码相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户密码
        body:
          multipart/form-data:
            properties:
              old:
                type: string
                description: 旧密码
                example: password123
                required: true
              new:
                type: string
                description: 新密码
                example: passcode123
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-password-put-return-sample.json
/course:
  description: 课程相关接口
  post:
    is: ["hasAuth"]
    description: 新建课程
    body:
      multipart/form-data:
        properties:
          title:
            type: string
            description: 课程标题
            example: 高等数学
            required: true
    responses:
      201:
        body:
          application/json:
            example: !include api-include-course-post-return-sample.json
  get:
    is: ["hasAuth"]
    description: 通过课程代码获取课程 id
    body:
      multipart/form-data:
        properties:
          code:
            type: string
            description: 课程代码
            example: 114514
            required: true
    responses:
      200:
        body:
          application/json:
            example: !include api-include-course-get-return-sample.json
  /{id}:
    uriParameters:
      id:
        description: 课程 id
        type: integer
    get:
      is: ["hasAuth"]
      description: 获取课程信息
      responses:
        200:
          body:
            application/json:
              example: !include api-include-course-id-get-return-sample.json
    put:
      is: ["hasAuth"]
      description: 更新课程信息
      body:
        multipart/form-data:
          properties:
            title:
              type: string
              description: 课程标题
              example: 高等数学
              required: true
      responses:
        201:
          body:
            application/json:
              example: !include api-include-course-id-put-return-sample.json
    delete:
      is: ["hasAuth"]
      description: 删除课程
      responses:
        200:
          body:
            application/json:
              example: !include api-include-course-id-delete-return-sample.json
    /student:
      get:
        is: ["hasAuth"]
        description: 获取学生列表
        responses:
          200:
            body:
              application/json:
                example: !include api-include-course-id-student-get-return-sample.json
      post:
        is: ["hasAuth"]
        description: 学生参加课程
        body:
          multipart/form-data:
            properties:
              studentId:
                type: string
                description: 学生 id
                example: 1
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-course-id-student-post-return-sample.json
      delete:
        is: ["hasAuth"]
        description: 学生退出课程
        body:
          multipart/form-data:
            properties:
              studentId:
                type: string
                description: 学生 id
                example: 1
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-course-id-student-delete-return-sample.json
    /task:
      description: 课程任务相关接口
      get:
        is: ["hasAuth"]
        description: 获取课程作业任务
        responses:
          200:
            body:
              application/json:
                example: !include api-include-course-id-task-get-return-sample.json
/task:
  description: 作业任务相关接口
  post:
    is: ["hasAuth"]
    description: 教师发布作业任务
    queryParameters:
      courseId:
        type: integer
        description: 课程 id
        example: 1
        required: true
    body:
      multipart/form-data:
        properties:
          title:
            type: string
            description: 标题
            example: 第一章作业
            required: true
          detail:
            type: stringd
            description: 作业内容
            example: 第一章课后习题 ......
            required: true
          type:
            type: integer
            description: |
              作业类型\
              0 图片\
              1 文档\
              2 程序
            example: 1
            required: true
          language:
            type: integer
            description: |
              程序语言\
              0 无 （不是程序作业）\
              1 Java\
              2 C/CPP\
              3 Python
            example: 0
            required: true
          deadLine:
            type: integer
            description: 截止时间（Unix时间）
            example: 1634219467
            required: true
    responses:
      200:
        body:
          application/json:
            example: !include api-include-task-post-return-sample.json
  /{id}:
    uriParameters:
      id:
        description: 作业任务 id
        type: integer
    get:
      is: ["hasAuth"]
      description: 获取作业任务信息
      responses:
        200:
          body:
            application/json:
              example: !include api-include-task-id-get-return-sample.json
    put:
      is: ["hasAuth"]
      description: 教师更新作业任务
    delete:
      is: ["hasAuth"]
      description: 教师删除作业任务
/homework:
  description: 学生作业相关接口
/file:
  description: 文件相关接口
  /task:
    post:
      description: 作业任务文件上传
      body:
        multipart/form-data:
          properties:
            file:
              type: file
              description: 文件
              require: true
      response:
        200:
          body:
            application/json:
              example: !include api-include-file-task-post-return-sample.json
  /homework:
    post:
      description: 学生作业文件上传
      body:
        multipart/form-data:
          properties:
            file:
              type: file
              description: 文件
              require: true
      response:
        200:
          body:
            application/json:
              example: !include api-include-file-homework-post-return-sample.json
