#%RAML 1.0
---
title: Plagiarism Identify Server
baseUri: http://example.com/api/{version}
version: v1


traits:
  hasAuth:
    headers:
      Authorization:
        type: string
        description: Bearer token
        example:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjEsIklzVGVhY2hlciI6dHJ1ZSwiZXhwIjoxNjMzNTMxNzU4LCJpYXQiOjE2MzM1MjQ1NTgsImlzcyI6ImFpbWVybmVpZ2UuY29tIiwic3ViIjoidXNlciB0b2tlbiJ9.EnJnAvSklGaem0bOllDCL1TI--yTFfs_WHU7qeOYhiw
        required: true

/login:
  description: 用户登录
  /teacher:
    description: 老师登录
    get:
      description: 登录获取 token
      body:
        multipart/form-data:
          properties:
            account:
              type: string
              description: 用户帐号
              example: 1907040101
              required: true
            password:
              type: string
              description: 用户密码
              example: password1234
              required: true
      responses:
        200:
          body:
            application/json:
              example: !include api-include-login-teacher-get-return-sample.json
  /student:
    description: 学生登录
    get:
      description: 登录获取 token
      body:
        multipart/form-data:
          properties:
            account:
              type: string
              description: 用户帐号
              example: 1907040101
              required: true
            password:
              type: string
              description: 用户密码
              example: password1234
              required: true
      responses:
        200:
          body:
            application/json:
              example: !include api-include-login-student-get-return-sample.json
/student:
  description: 学生相关接口
  post:
    description: 注册学生帐号
    body:
      multipart/form-data:
        properties:
          account:
            type: string
            description: 用户帐号
            example: 1907040101
            required: true
          password:
            type: string
            description: 用户密码
            example: password1234
            required: true
    responses:
      201:
        body:
          application/json:
            example: !include api-include-student-post-return-sample.json
/teacher:
  description: 教师相关接口
  post:
    description: 注册教师帐号
    body:
      multipart/form-data:
        properties:
          account:
            type: string
            description: 用户帐号
            example: 1907040101
            required: true
          password:
            type: string
            description: 用户密码
            example: password1234
            required: true
    responses:
      201:
        body:
          application/json:
            example: !include api-include-teacher-post-return-sample.json
  /{id}:
    uriParameters:
      id:
        description: 用户 id
        type: integer
    get:
      is: ["hasAuth"]
      description: 获取教师信息
      responses:
        200:
          body:
            application/json:
              example: !include api-include-teacher-id-get-return-sample.json
    put:
      is: ["hasAuth"]
      description: 更新教师信息
      body:
        multipart/form-data:
          properties:
            name:
              type: string
              description: 姓名
              example: 张三
              required: true
            phone:
              type: string
              description: 手机号
              example: 13735667891
              required: true
            email:
              type: string
              description: 邮箱
              example: user@example.com
              required: true
      responses:
        200:
          body:
            application/json:
              example: !include api-include-teacher-id-put-return-sample.json
    delete:
      is: ["hasAuth"]
      description: 注销教师帐号
      responses:
        200:
          body:
            application/json:
              example: !include api-include-teacher-id-delete-return-sample.json
    /avatar:
      description: 用户头像相关接口
      get:
        is: ["hasAuth"]
        description: 获取用户头像
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-avatar-get-return-sample.json
      put:
        is: ["hasAuth"]
        description: 修改用户头像
        body:
          multipart/form-data:
            properties:
              avatar:
                type: file
                fileTypes: ['image/jpeg', 'image/png']
                maxLength: 307200
                description: 头像
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-avatar-put-return-sample.json
    /name:
      description: 用户姓名相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户姓名
        body:
          multipart/form-data:
            properties:
              name:
                type: string
                description: 姓名
                example: 张三
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-name-put-return-sample.json
    /phone:
      description: 用户手机号相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户手机号
        body:
          multipart/form-data:
            properties:
              phone:
                type: string
                description: 手机号
                example: 13735667891
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-phone-put-return-sample.json
    /email:
      description: 用户邮箱相关接口
      put:
        is: ["hasAuth"]
        description: 修改用户邮箱
        body:
          multipart/form-data:
            properties:
              email:
                type: string
                description: 邮箱
                example: user@example.com
                required: true
        responses:
          200:
            body:
              application/json:
                example: !include api-include-teacher-id-email-put-return-sample.json
/homework:
/file:
  /upload:
  /download:
